name: dimple
description: Simple Dependency Injection & Service Container
version: 0.1.0-beta.1
authors:
  - Roman Shamritskiy <roman@litgroup.ru>
  - Vladimir Bogutskiy <ustas@litgroup.ru>
homepage: https://github.com/Dartiny/dimple
environment:
  sdk: '>=1.10.0 <2.0.0'
dev_dependencies:
  test: '^0.12.3'
  mockito: '^0.10.1'
